---
- hosts: all
  become: yes
  tasks:
    -  name: install apache2 by apt model
       apt: 
         name: apche2
         state: present
       where: ansible_os_family=="Debian"

    -  name: install apache2 by service model
       service:
         name: apache2
         state: started
       where: ansible_os_family=="Debian"