---
- hosts: all
  become: yes
  tasks:
      - name: install apache2 by apt model
        apt: 
         name: apche2
         state: present
        when: ansible_os_family=="Debian"

      - name: install apache2 by service model
        service:
         name: apache2
         state: started
        when: ansible_os_family=="Debian"