---
- hosts: 172.31.19.28
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: copy the index file on ansible node side
    copy:
      src: myindexfile
      dest:  /var/www/html/index.html
      
